// Structured unit datasheet entries, rendered by the macros in
// _includes/datasheet-parts.njk. Facts (stats, keywords, weapons, traits)
// live here; narrative asides (like the Tyrant Guard loadout note) are
// written directly in the page template instead, since they don't reduce
// to a data field cleanly.
//
// keywords: { type: "plain", text } for a bare keyword, or
//           { type: "ref", ref } to look up _data/abilityTips.js.
// weapons[].tags: an array of ability-tip ids (may be empty).
module.exports = [
  {
    id: "tyranids-parasite-of-mortrex",
    factionSlug: "tyranids",
    group: "assault-brood",
    name: "Parasite of Mortrex",
    modelCount: null,
    stats: { m: "12″", t: "5", sv: "4+", w: "5", ld: "6+", oc: "1" },
    keywords: [
      { type: "plain", text: "Infantry" },
      { type: "plain", text: "Character" },
      { type: "ref", ref: "fly" },
      { type: "ref", ref: "synapse-parasite" },
      { type: "ref", ref: "shadow-in-the-warp" },
      { type: "ref", ref: "deep-strike" },
      { type: "ref", ref: "lone-operative" },
      { type: "ref", ref: "stealth" },
    ],
    weapons: [
      {
        id: "barbed-ovipositor",
        name: "Barbed ovipositor",
        tags: ["anti-infantry-3", "extra-attacks"],
        range: "Melee",
        attacks: "2",
        skill: "2+",
        strength: "3",
        ap: "-2",
        damage: "3",
      },
      {
        id: "clawed-limbs",
        name: "Clawed limbs",
        tags: [],
        range: "Melee",
        attacks: "6",
        skill: "2+",
        strength: "5",
        ap: "-1",
        damage: "1",
      },
    ],
    traits: [
      {
        name: "It Itches!",
        body: "At the start of the Fight phase, force one enemy unit within range to take a battle-shock test.",
      },
    ],
    order: 1,
  },
  {
    id: "tyranids-genestealers",
    factionSlug: "tyranids",
    group: "assault-brood",
    name: "Genestealers",
    modelCount: 10,
    stats: { m: "8″", t: "4", sv: "5+", w: "2", ld: "7+", oc: "1" },
    keywords: [
      { type: "plain", text: "Infantry" },
      { type: "ref", ref: "synapse" },
      { type: "plain", text: "5+ Invulnerable save" },
    ],
    weapons: [
      {
        id: "genestealer-claws-and-talons",
        name: "Genestealer claws and talons",
        tags: [],
        range: "Melee",
        attacks: "4",
        skill: "2+",
        strength: "4",
        ap: "-2",
        damage: "1",
      },
    ],
    traits: [
      {
        name: "Patrol Squads",
        body: "Can split into two 5-model units before the battle, and Scouts 8″ ahead at deployment.",
      },
      {
        name: "Vanguard Predator",
        body: "Re-roll a Hit roll of 1; also re-roll a Wound roll of 1 when attacking near an objective marker.",
      },
    ],
    order: 2,
  },
  {
    id: "tyranids-biovore",
    factionSlug: "tyranids",
    group: "assault-brood",
    name: "Biovore",
    modelCount: null,
    stats: { m: "5″", t: "6", sv: "3+", w: "5", ld: "8+", oc: "1" },
    keywords: [
      { type: "plain", text: "Infantry" },
      { type: "ref", ref: "synapse" },
    ],
    weapons: [
      {
        id: "spore-mine-launcher",
        name: "Spore Mine launcher",
        tags: ["blast", "devastating-wounds", "heavy"],
        range: "48″",
        attacks: "D3",
        skill: "4+",
        strength: "6",
        ap: "-1",
        damage: "2",
      },
      {
        id: "chitin-barbed-limbs",
        name: "Chitin-barbed limbs",
        tags: [],
        range: "Melee",
        attacks: "2",
        skill: "4+",
        strength: "5",
        ap: "0",
        damage: "1",
      },
    ],
    traits: [
      {
        name: "Deadly Demise 1",
        body: "Explodes when destroyed and can damage nearby units — don't cluster your own models around it.",
      },
    ],
    order: 3,
  },
  {
    id: "tyranids-tyrant-guard",
    factionSlug: "tyranids",
    group: "assault-brood",
    name: "Tyrant Guard",
    modelCount: 3,
    stats: { m: "6″", t: "8", sv: "3+", w: "4", ld: "8+", oc: "1" },
    keywords: [
      { type: "plain", text: "Infantry" },
      { type: "ref", ref: "synapse" },
    ],
    weapons: [
      {
        id: "bone-cleaver-lash-whip-and-rending-claws",
        name: "Bone cleaver, lash whip and rending claws",
        tags: [],
        range: "Melee",
        attacks: "3",
        skill: "3+",
        strength: "5",
        ap: "-1",
        damage: "2",
      },
      {
        id: "crushing-claws-and-rending-claws",
        name: "Crushing claws and rending claws",
        tags: ["twin-linked"],
        range: "Melee",
        attacks: "2",
        skill: "4+",
        strength: "8",
        ap: "-2",
        damage: "2",
      },
      {
        id: "scything-talons-and-rending-claws",
        name: "Scything talons and rending claws",
        tags: [],
        range: "Melee",
        attacks: "5",
        skill: "3+",
        strength: "5",
        ap: "-1",
        damage: "1",
      },
    ],
    traits: [],
    order: 4,
  },
  {
    id: "league-of-votann-vynn-bane-slayer",
    factionSlug: "league-of-votann",
    group: "bane-slayers-bulwark",
    name: "Vynn Bane-Slayer",
    modelCount: null,
    stats: { m: "5″", t: "5", sv: "2+", w: "5", ld: "7+", oc: "1" },
    keywords: [
      { type: "plain", text: "5+ Invulnerable save" },
      { type: "ref", ref: "assault" },
      { type: "plain", text: "Leader (attaches to Einhyr Hearthguard)" },
    ],
    weapons: [
      {
        id: "autoch-pattern-combi-bolter",
        name: "Autoch-pattern combi-bolter",
        tags: [],
        range: "24″",
        attacks: "4",
        skill: "2+",
        strength: "4",
        ap: "0",
        damage: "1",
      },
      {
        id: "mass-hammer",
        name: "Mass hammer",
        tags: [],
        range: "Melee",
        attacks: "3",
        skill: "3+",
        strength: "12",
        ap: "-3",
        damage: "D6+1",
      },
    ],
    traits: [],
    order: 1,
  },
  {
    id: "league-of-votann-einhyr-hearthguard",
    factionSlug: "league-of-votann",
    group: "bane-slayers-bulwark",
    name: "Einhyr Hearthguard",
    modelCount: 5,
    stats: { m: "5″", t: "5", sv: "2+", w: "2", ld: "7+", oc: "1" },
    keywords: [{ type: "plain", text: "5+ Invulnerable save" }],
    weapons: [
      {
        id: "exoarmour-grenade-launcher",
        name: "Exoarmour grenade launcher",
        tags: ["blast-votann"],
        range: "24″",
        attacks: "D3",
        skill: "3+",
        strength: "3",
        ap: "0",
        damage: "1",
      },
      {
        id: "volkanite-disintegrator",
        name: "Volkanite disintegrator",
        tags: ["devastating-wounds"],
        range: "24″",
        attacks: "3",
        skill: "3+",
        strength: "5",
        ap: "0",
        damage: "1",
      },
      {
        id: "graviton-hammer",
        name: "Graviton hammer (Hesyr only)",
        tags: ["anti-monster-vehicle-3"],
        range: "Melee",
        attacks: "3",
        skill: "4+",
        strength: "9",
        ap: "-1",
        damage: "3",
      },
      {
        id: "plasma-blade-gauntlet",
        name: "Plasma blade gauntlet",
        tags: [],
        range: "Melee",
        attacks: "3",
        skill: "3+",
        strength: "6",
        ap: "-2",
        damage: "1",
      },
    ],
    traits: [],
    order: 2,
  },
  {
    id: "league-of-votann-hearthkyn-warriors",
    factionSlug: "league-of-votann",
    group: "bane-slayers-bulwark",
    name: "Hearthkyn Warriors",
    modelCount: 10,
    stats: { m: "5″", t: "5", sv: "4+", w: "1", ld: "7+", oc: "2" },
    keywords: [{ type: "plain", text: "5+ Invulnerable save" }],
    weapons: [
      {
        id: "autoch-pattern-bolt-pistol",
        name: "Autoch-pattern bolt pistol",
        tags: ["close-quarters"],
        range: "12″",
        attacks: "1",
        skill: "4+",
        strength: "4",
        ap: "0",
        damage: "1",
      },
      {
        id: "hylas-auto-rifle",
        name: "HYLas auto rifle (1 model)",
        tags: ["assault", "rapid-fire-3"],
        range: "24″",
        attacks: "3",
        skill: "4+",
        strength: "6",
        ap: "-1",
        damage: "1",
      },
      {
        id: "magna-rail-rifle",
        name: "Magna-rail rifle (1 model)",
        tags: ["devastating-wounds", "heavy-votann"],
        range: "18″",
        attacks: "1",
        skill: "5+",
        strength: "12",
        ap: "-3",
        damage: "D3+3",
      },
      {
        id: "ion-blaster",
        name: "Ion blaster (up to 6 models)",
        tags: [],
        range: "18″",
        attacks: "3",
        skill: "3+",
        strength: "5",
        ap: "0",
        damage: "1",
      },
      {
        id: "theyns-pistol",
        name: "Theyn's pistol (Theyn only)",
        tags: ["close-quarters"],
        range: "12″",
        attacks: "1",
        skill: "4+",
        strength: "8",
        ap: "-2",
        damage: "1",
      },
      {
        id: "armoured-fists",
        name: "Armoured fists",
        tags: [],
        range: "Melee",
        attacks: "1",
        skill: "4+",
        strength: "4",
        ap: "0",
        damage: "1",
      },
      {
        id: "plasma-knife",
        name: "Plasma knife",
        tags: [],
        range: "Melee",
        attacks: "2",
        skill: "4+",
        strength: "4",
        ap: "-2",
        damage: "1",
      },
      {
        id: "theyns-armaments",
        name: "Theyn's armaments (Theyn only)",
        tags: [],
        range: "Melee",
        attacks: "2",
        skill: "4+",
        strength: "5",
        ap: "-2",
        damage: "2",
      },
    ],
    traits: [],
    order: 3,
  },
  {
    id: "league-of-votann-brokhyr-thunderkyn",
    factionSlug: "league-of-votann",
    group: "bane-slayers-bulwark",
    name: "Brokhyr Thunderkyn",
    modelCount: 3,
    stats: { m: "5″", t: "6", sv: "3+", w: "2", ld: "7+", oc: "1" },
    keywords: [],
    weapons: [
      {
        id: "sp-conversion-beamer",
        name: "SP conversion beamer",
        tags: ["lethal-hits"],
        range: "24″",
        attacks: "2",
        skill: "4+",
        strength: "7",
        ap: "-2",
        damage: "3",
      },
      {
        id: "powered-strikes",
        name: "Powered strikes",
        tags: [],
        range: "Melee",
        attacks: "2",
        skill: "4+",
        strength: "4",
        ap: "0",
        damage: "1",
      },
    ],
    traits: [],
    order: 4,
  },
];
